import Head from "next/head";
import Image from "next/image";
import { Row, Col, Container, Button } from "react-bootstrap";
import styles from "@/styles/Home.module.scss";
import Link from "next/link";
// import Image from "next/image";
import { RightIcon, right_arrow } from "utlis/icons";

export default function Home() {
  const jobs = [
    {
      company: "Acme Corporation",
      location: "San Francisco, CA",
      title: "Frontend Developer",
      description:
        "We are seeking a talented frontend developer to join our team.",
      salary: "NRs. 25000",
      image: "#",
      type: "full time",
    },
    {
      company: "Globex Corporation",
      location: "New York, NY",
      title: "Backend Developer",
      description:
        "We are seeking an experienced backend developer to help us scale our platform.",
      salary: "NRs. 25000",
      image: "#",
      type: "full time",
    },
    {
      company: "Acme Corporation",
      location: "San Francisco, CA",
      title: "Frontend Developer",
      description:
        "We are seeking a talented frontend developer to join our team.",
      salary: "NRs. 25000",
      image: "#",
      type: "full time",
    },
    {
      company: "Globex Corporation",
      location: "New York, NY",
      title: "Backend Developer",
      description:
        "We are seeking an experienced backend developer to help us scale our platform.",
      salary: "NRs. 25000",
      image: "#",
      type: "full time",
    },
  ];

  return (
    <>
      <Head>
        <title>Job Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className={styles.hero_grid}>
          <div className={styles.text_section}>
            <h1>
              Your Dream <span>Job Is Waiting</span>
            </h1>
            <h2>5000 + Jobs</h2>
            <div className={styles.search}>
              <Image
                src="icons/search.svg"
                alt="search icon"
                height={25}
                width={25}
              />
              <input type="text" placeholder="Enter job title, keyword" />
              <div className={styles.sperate_line}></div>
              <Image
                src="icons/loc.svg"
                alt="location icon"
                height={25}
                width={25}
              />
              <input type="text" placeholder="Enter job title, keyword" />
              <span className={styles.search_button}>Search</span>
            </div>
          </div>
          <div className={styles.heroImage}>
            <Image src="images/landingPage/hero.svg" alt="hero" layout="fill" />
          </div>
        </div>
      </Container>
      <section className={styles.category_section}>
        <Container>
          <div className={styles.header}>
            <h2>
              Explore by <span>categories</span>
            </h2>
            <Link href="jobs">Show all jobs {RightIcon}</Link>
          </div>
          <div className={styles.cards_grid}>
            {Array.from({ length: 8 }).map((x, i) => (
              <div className={styles.card} key={`cat-${i}`}>
                <Image src={`icons/${i + 1}.svg`} height={60} width={60} />
                <div className={styles.title}>Design</div>
                <div className={styles.description}>
                  <Link href={"/"}>256+ jobs available {RightIcon}</Link>
                </div>
              </div>
            ))}
          </div>
        </Container>
      </section>
      <div className={styles.featuredJobs}>
        <div className={`${styles.subscribe}`}>
          <h1 styles={styles.lg}>
            Get <span>Job Alerts</span> ?
          </h1>
          <div className={`${styles.input}`}>
            <input type="text" name="" id="" />
            <button>Subscribe</button>
          </div>
        </div>
        <div className={`${styles.title}`}>
          <h1>
            Featured <span>Jobs</span>
          </h1>
          <a href="#">Show all Jobs {right_arrow}</a>
        </div>
        <JobList jobs={jobs} />
      </div>
    </>
  );
}

const JobCard = ({ job }) => {
  return (
    <div className={styles.job_card}>
      <div className={`${styles.head}`}>
        <img src={job.image} title="Company profile" />
        <div>
          <h2>{job.company}</h2>
          <p>{job.location}</p>
        </div>
      </div>
      <div className="body">
        <p>{job.type}</p>
        <h3 className={styles.apply}>{job.title}</h3>
        <p>{job.description}</p>
      </div>

      <div className={styles.foot}>
        <p>{job.salary}</p>
        <a href="#">Apply Now</a>
      </div>
    </div>
  );
};

const JobList = ({ jobs }) => {
  return (
    <div className={styles.job_list}>
      {jobs.map((job) => (
        <JobCard key={job.title} job={job} />
      ))}
    </div>
  );
};
