const applicantArray = [
    {
        id: 1,
        checked: true,
        title: "Huma Therman",
        companyName: "Codinglimits Pvt Ltd.",
        experience: "5y 3m",
        minSalary: "15 lac",
        maxSalary: "25 lac",
        address: "Haryana",
        postedTime: "25 days+",
        branches: "Hyderabad, Mumbai, Kolkata, Delhi ...",
    },
    {
        id: 2,
        checked: false,
        title: "John Doe",
        companyName: "Tech Innovators Inc.",
        experience: "7y 2m",
        minSalary: "18 lac",
        maxSalary: "30 lac",
        address: "Bangalore",
        postedTime: "20 days+",
        branches: "Bangalore, Pune, Chennai, Mumbai ...",
    },
    {
        id: 3,
        checked: false,
        title: "Alice Smith",
        companyName: "Infinite Coders Ltd.",
        experience: "4y 6m",
        minSalary: "12 lac",
        maxSalary: "22 lac",
        address: "Delhi",
        postedTime: "15 days+",
        branches: "Delhi, Noida, Gurgaon, Faridabad ...",
    },
    {
        id: 4,
        checked: true,
        title: "Bob Johnson",
        companyName: "TechSolutions Co.",
        experience: "6y 8m",
        minSalary: "20 lac",
        maxSalary: "35 lac",
        address: "Mumbai",
        postedTime: "18 days+",
        branches: "Mumbai, Pune, Thane, Navi Mumbai ...",
    },
    {
        id: 5,
        checked: false,
        title: "Samantha Lee",
        companyName: "Digital Innovations Ltd.",
        experience: "3y 9m",
        minSalary: "14 lac",
        maxSalary: "26 lac",
        address: "Chennai",
        postedTime: "22 days+",
        branches: "Chennai, Bangalore, Hyderabad, Coimbatore ...",
    }
]